version: '3.9'

services:

  # mysql-db:
  #   image: mysql
  #   container_name: mysql-db
  #   restart: always
  #   environment:
  #     MYSQL_USER: towlschii
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: towlschii_utilities_database
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  # postgres-db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: towlschii_utilities_database
  #     POSTGRES_USER: towlschii
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    container_name: backend-container
    environment:
      SUPER_USER: towlschii
      SUPER_PASSWORD: password

volumes:
  mysql_data:
  postgres_data:
