name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_USERNAME
        
    - name: Build the Docker image
      run: docker build -t tuw-backend ./backend
    - name: Push to Docker Hub
      run: docker push itsjustpritam123/tuw-backend:$(date +%s)
