name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
        IMAGE_TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v4
    - name: Login Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

    - name: Set up an environment variable for image tag
      id: vars
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      
    - name: Build and push Docker image
      run: |
        docker build -t itsjustpritam123/tuw-backend:${{ env.IMAGE_TAG }} ./backend
        docker push itsjustpritam123/tuw-backend:${{ env.IMAGE_TAG }}
